/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/games/{game_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_games_get_game_state'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/replay.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Return a JSON replay of a terminal game. Refused (403) for in-progress
     *     games — the model would expose hidden hands. Resolves `viewer_seat` from
     *     the auth `Identity` so clients can orient the replay to the viewer.
     *
     *     `identity` is `OptionalIdentity` (a newtype over `Option<Identity>`) so
     *     that a request with a present-but-unrecognized Bearer token (e.g. a
     *     revoked API token) still receives the replay with `viewer_seat: null`
     *     rather than a 401. No-credential and cookie-session paths still resolve
     *     to `Some(Anonymous)` or `Some(Registered)` as before; only the
     *     invalid-Bearer case changes from 401 → 200-with-null-seat.
     */
    get: operations['handlers_games_get_replay_json'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/transition': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['handlers_games_make_transition'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/players/{player_id}/hand': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_games_get_hand'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/by-short-id/{short_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_games_get_game_by_short_id_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/by-player-url/{url_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_games_get_game_by_player_url'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/presence': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_games_get_presence'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/matchmaking/seeks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_matchmaking_list_seeks_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/matchmaking/queue-sizes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_matchmaking_queue_sizes_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/challenges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_challenges_list_challenges_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/challenges/{challenge_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_challenges_get_challenge_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/challenges/by-short-id/{short_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['handlers_challenges_get_challenge_by_short_id_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Intuitive card struct. Ordered by suit (Club < Diamond < Heart < Spade),
     *     then rank ascending — the derived lexicographic order over the fields.
     */
    Card: {
      suit: components['schemas']['Suit'];
      rank: components['schemas']['Rank'];
    };
    /** @description Configuration for creating a challenge. */
    ChallengeConfig: {
      max_points: number;
      timer_config?: components['schemas']['TimerConfig'];
      creator_seat?: components['schemas']['Seat'];
      creator_name?: string | null;
      expiry_secs: number;
    };
    ChallengeStatusKind:
      | {
          /** Format: uuid */
          game_id: string;
          /** @enum {string} */
          status: 'started';
        }
      | {
          /** @enum {string} */
          status: 'open' | 'cancelled' | 'expired';
        };
    ChatRequest: {
      /** Format: uuid */
      player_id: string;
      content: string;
    };
    CreateGameRequest: {
      max_points: number;
      timer_config?: components['schemas']['TimerConfig'];
      num_humans?: number | null;
    };
    /** @description One hand in a `Deal` event: the target seat/pile and the cards dealt to it. */
    DealtHand: {
      target: string;
      cards: components['schemas']['Card'][];
    };
    Deck: {
      suits: string[];
      ranks: string[];
    };
    ErrorResponse: {
      error: string;
    };
    Event:
      | {
          hands: components['schemas']['DealtHand'][];
          /** @enum {string} */
          type: 'deal';
        }
      | {
          start: string;
          values: string[];
          /** @enum {string} */
          type: 'call';
        }
      | {
          leader: string;
          cards: components['schemas']['Card'][];
          /** @enum {string} */
          type: 'play';
        }
      | {
          from: string;
          to: string;
          cards: components['schemas']['Card'][];
          /** @enum {string} */
          type: 'exchange';
        }
      | {
          target: string;
          cards: components['schemas']['Card'][];
          /** @enum {string} */
          type: 'reveal';
        };
    /**
     * @description JSON replay response for a terminal game — available at
     *     `GET /games/{game_id}/replay.json`.
     */
    GameReplayResponse: {
      model: components['schemas']['Model'];
      cumulative_by_round: number[][];
      viewer_seat?: number | null;
      termination: components['schemas']['ReplayTermination'];
    };
    /** @description Response for getting a player's hand */
    HandResponse: {
      /** Format: uuid */
      player_id: string;
      cards: components['schemas']['Card'][];
    };
    JoinChallengeRequest: {
      name?: string | null;
    };
    Meta: {
      version: number;
      game_hint?: string | null;
      seats: string[];
      dealer?: string | null;
      players: (string | null)[];
      partnerships?: string[][] | null;
      caps: string[];
    };
    Model: {
      meta: components['schemas']['Meta'];
      deck: components['schemas']['Deck'];
      events: components['schemas']['Event'][];
    };
    /** @description A player's name entry */
    PlayerNameEntry: {
      /** Format: uuid */
      player_id: string;
      name?: string | null;
    };
    PlayerPresenceEntry: {
      /** Format: uuid */
      player_id: string;
      connected: boolean;
    };
    PlayerUrlResponse: {
      /** Format: uuid */
      game_id: string;
      /** Format: uuid */
      player_id: string;
      player_short_id: string;
      game: {
        /** Format: uuid */
        game_id: string;
        short_id: string;
        state:
          | {
              Betting: number;
            }
          | {
              Trick: number;
            }
          | ('NotStarted' | 'Completed' | 'Aborted');
        team_a_score?: number | null;
        team_b_score?: number | null;
        team_a_bags?: number | null;
        team_b_bags?: number | null;
        /** Format: uuid */
        current_player_id?: string | null;
        player_names: {
          /** Format: uuid */
          player_id: string;
          name?: string | null;
        }[];
        /** @description Fischer increment timer configuration (X+Y: X minutes initial, Y seconds increment per move). */
        timer_config?: {
          initial_time_secs: number;
          increment_secs: number;
        } | null;
        player_clocks_ms?: number[];
        active_player_clock_ms?: number | null;
        table_cards?: {
          suit: components['schemas']['Suit'];
          rank: components['schemas']['Rank'];
        }[];
        player_bets?: number[];
        player_tricks_won?: number[];
        /** Format: uuid */
        last_trick_winner_id?: string | null;
        last_completed_trick?: {
          suit: components['schemas']['Suit'];
          rank: components['schemas']['Rank'];
        }[];
      };
      hand: components['schemas']['HandResponse'];
    };
    PresenceSnapshot: {
      /** Format: uuid */
      game_id: string;
      players: components['schemas']['PlayerPresenceEntry'][];
      spectator_count: number;
    };
    /** @description Queue size for a specific game configuration (max_points + timer_config). */
    QueueSizeEntry: {
      max_points: number;
      timer_config: components['schemas']['TimerConfig'];
      waiting: number;
    };
    /** @enum {string} */
    Rank:
      | 'Two'
      | 'Three'
      | 'Four'
      | 'Five'
      | 'Six'
      | 'Seven'
      | 'Eight'
      | 'Nine'
      | 'Ten'
      | 'Jack'
      | 'Queen'
      | 'King'
      | 'Ace';
    /** @enum {string} */
    ReplayTermination: 'completed' | 'aborted';
    /** @enum {string} */
    Seat: 'A' | 'B' | 'C' | 'D';
    /** @description Per-seat snapshot sent in SSE events. */
    SeatInfo: {
      seat: components['schemas']['Seat'];
      /** Format: uuid */
      player_id: string;
      name?: string | null;
    };
    SeekRequest: {
      max_points: number;
      timer_config: components['schemas']['TimerConfig'];
      name?: string | null;
    };
    /** @description Summary of seeks waiting for a given max_points */
    SeekSummary: {
      max_points: number;
      waiting: number;
    };
    SessionPlayerResponse: {
      /** Format: uuid */
      user_id: string;
      display_name?: string | null;
    };
    SetDisplayNameRequest: {
      name?: string | null;
    };
    SetNameRequest: {
      name?: string | null;
    };
    State:
      | {
          Betting: number;
        }
      | {
          Trick: number;
        }
      | ('NotStarted' | 'Completed' | 'Aborted');
    /** @enum {string} */
    Suit: 'Club' | 'Diamond' | 'Heart' | 'Spade';
    /** @description Fischer increment timer configuration (X+Y: X minutes initial, Y seconds increment per move). */
    TimerConfig: {
      initial_time_secs: number;
      increment_secs: number;
    };
    TransitionRequest: Record<string, never>;
    TransitionResponse: {
      success: boolean;
      result: string;
    };
    TransitionType:
      | {
          amount: number;
          /** @enum {string} */
          type: 'bet';
        }
      | {
          card: components['schemas']['Card'];
          /** @enum {string} */
          type: 'card';
        }
      | {
          /** @enum {string} */
          type: 'start';
        };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  handlers_games_get_game_state: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            game_id: string;
            short_id: string;
            state:
              | {
                  Betting: number;
                }
              | {
                  Trick: number;
                }
              | ('NotStarted' | 'Completed' | 'Aborted');
            team_a_score?: number | null;
            team_b_score?: number | null;
            team_a_bags?: number | null;
            team_b_bags?: number | null;
            /** Format: uuid */
            current_player_id?: string | null;
            player_names: {
              /** Format: uuid */
              player_id: string;
              name?: string | null;
            }[];
            /** @description Fischer increment timer configuration (X+Y: X minutes initial, Y seconds increment per move). */
            timer_config?: {
              initial_time_secs: number;
              increment_secs: number;
            } | null;
            player_clocks_ms?: number[];
            active_player_clock_ms?: number | null;
            table_cards?: {
              suit: components['schemas']['Suit'];
              rank: components['schemas']['Rank'];
            }[];
            player_bets?: number[];
            player_tricks_won?: number[];
            /** Format: uuid */
            last_trick_winner_id?: string | null;
            last_completed_trick?: {
              suit: components['schemas']['Suit'];
              rank: components['schemas']['Rank'];
            }[];
          };
        };
      };
    };
  };
  handlers_games_get_replay_json: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameReplayResponse'];
        };
      };
    };
  };
  handlers_games_make_transition: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransitionResponse'];
        };
      };
    };
  };
  handlers_games_get_hand: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
        player_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandResponse'];
        };
      };
    };
  };
  handlers_games_get_game_by_short_id_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        short_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            game_id: string;
            short_id: string;
            state:
              | {
                  Betting: number;
                }
              | {
                  Trick: number;
                }
              | ('NotStarted' | 'Completed' | 'Aborted');
            team_a_score?: number | null;
            team_b_score?: number | null;
            team_a_bags?: number | null;
            team_b_bags?: number | null;
            /** Format: uuid */
            current_player_id?: string | null;
            player_names: {
              /** Format: uuid */
              player_id: string;
              name?: string | null;
            }[];
            /** @description Fischer increment timer configuration (X+Y: X minutes initial, Y seconds increment per move). */
            timer_config?: {
              initial_time_secs: number;
              increment_secs: number;
            } | null;
            player_clocks_ms?: number[];
            active_player_clock_ms?: number | null;
            table_cards?: {
              suit: components['schemas']['Suit'];
              rank: components['schemas']['Rank'];
            }[];
            player_bets?: number[];
            player_tricks_won?: number[];
            /** Format: uuid */
            last_trick_winner_id?: string | null;
            last_completed_trick?: {
              suit: components['schemas']['Suit'];
              rank: components['schemas']['Rank'];
            }[];
          };
        };
      };
    };
  };
  handlers_games_get_game_by_player_url: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        url_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlayerUrlResponse'];
        };
      };
    };
  };
  handlers_games_get_presence: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PresenceSnapshot'];
        };
      };
    };
  };
  handlers_matchmaking_list_seeks_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeekSummary'][];
        };
      };
    };
  };
  handlers_matchmaking_queue_sizes_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QueueSizeEntry'][];
        };
      };
    };
  };
  handlers_challenges_list_challenges_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            challenge_id: string;
            short_id: string;
            max_points: number;
            seats_filled: number;
            seats: ({
              seat: components['schemas']['Seat'];
              /** Format: uuid */
              player_id: string;
              name?: string | null;
            } | null)[];
          }[];
        };
      };
    };
  };
  handlers_challenges_get_challenge_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challenge_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            challenge_id: string;
            short_id: string;
            max_points: number;
            /** @description Fischer increment timer configuration (X+Y: X minutes initial, Y seconds increment per move). */
            timer_config?: {
              initial_time_secs: number;
              increment_secs: number;
            } | null;
            seats: ({
              seat: components['schemas']['Seat'];
              /** Format: uuid */
              player_id: string;
              name?: string | null;
            } | null)[];
            status: string;
            /** Format: uuid */
            game_id?: string | null;
            expires_at_epoch_secs: number;
          };
        };
      };
    };
  };
  handlers_challenges_get_challenge_by_short_id_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        short_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            challenge_id: string;
            short_id: string;
            max_points: number;
            /** @description Fischer increment timer configuration (X+Y: X minutes initial, Y seconds increment per move). */
            timer_config?: {
              initial_time_secs: number;
              increment_secs: number;
            } | null;
            seats: ({
              seat: components['schemas']['Seat'];
              /** Format: uuid */
              player_id: string;
              name?: string | null;
            } | null)[];
            status: string;
            /** Format: uuid */
            game_id?: string | null;
            expires_at_epoch_secs: number;
          };
        };
      };
    };
  };
}
